# Generated by Django 4.0.6 on 2022-07-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_jobpostactivity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostactivity',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.applicationstatus'),
        ),
    ]
